export enum StatutDemande {
  EN_ATTENTE_SENIOR = 'EN_ATTENTE_SENIOR',
  VALIDEE_SENIOR = 'VALIDEE_SENIOR',
  REJETEE_SENIOR = 'REJETEE_SENIOR',
  VALIDE_MONETIQUE = 'VALIDE_MONETIQUE',
  REJETE_MONETIQUE = 'REJETE_MONETIQUE',
  LIVREE = 'LIVREE',
}